### ISSUE TITLE
#pragma once is more better than include guard

### ISSUE THREAD

**Issue by fu7mu4** [exercism/xc#102]
if we use modern c compiler, use #pragma once instead of old style #ifndef -- #endif .
macro names starting with one or two underscores, such as _HELLO_WORLD_H and __HELLO_WORLD_H, are reserved to the implementation and should not be used by the user.

````c
#pragma once

void hello(char *buffer, const char *name);

````

````c
#ifndef _HELLO_WORLD_H
#define _HELLO_WORLD_H

void hello(char *buffer, const char *name);

#endif
````

**Comment by ryanplusplus** [comment]
@patricksjackson @palisaide what are you thoughts on this? I'm okay with making the change to `#pragma once` unless you're aware of any common incompatibilities.

**Comment by patricksjackson** [comment]
My only concern is that `#pragma once` isn't technically standard (because of issues that this repo will probably never encounter). If we're trying to showcase standard C practices, it may be best to stick with include guards.

I don't have strong feelings either way.

**Comment by ryanplusplus** [comment]
Good call, I didn't realize it wasn't standard. I figured it was part of a C standard newer than I'm used to in the embedded world.

**Comment by fu7mu4** [comment]
but _HELLO_WORLD_H is not legal, you know. we have better use HELLO_WORLD_H if you want not to use pragma once.

**Comment by ryanplusplus** [comment]
Understood. We will use a legal include guard and avoid the non-standard `#pragma once`.

**Comment by patricksjackson** [comment]
@fu7mu4 - Thanks for bringing these points up.
