### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by jjrabat** [exercism/xc#106]
How about including a .gitignore in each exercise containing tests.out?

**Comment by ryanplusplus** [comment]
What would be the purpose? This repository has `*.out` ignored globally and when using the `exercism` CLI it's not using git.

If the purpose is to add a `.gitignore` just in case track participants are using git to save their solutions, why wouldn't we also add ignore files for SVN, CVS, Mercurial, Perforce, RCS, SCS, etc.?

**Comment by jjrabat** [comment]
I think Exercism users are more likely to be using git than any other VCS... maybe not a very compelling argument :grin:

I brought this up because the Rust exercises all include a `.gitignore`. But now looking the other tracks I see this isn't standard, so I'll close this.
