### ISSUE TITLE
indent.sh does not match indent -linux -i3

### ISSUE THREAD

**Issue by wolf99** [exercism/xc#118]
The `README.md` suggests use of `$ indent -linux -i3`. this does not match what is produced by `indent.sh` however. as the CI uses `indent.sh` to verify the indent on files then this causes problems for those that read the readme and simply ran the `indent` command as suggested.

This can be seen in commit a5d8645 on which I ran `$ indent -linux -i3 $(file)`. This found a small braces spacing issue and corrected it. Thinking all was good I commited, pushed and made the PR to start the CI. But the CI reported that `verify-indent` failed! To see what the issue was I tried running `$ indent.sh $(file)` which made another, *different*, spacing change. This committed as 1f32a18 and subsequently passed the CI test.

I haven't tested this out but it seems that the options used in indent.sh differ from the Linux style (as specified by man indent), not only by `-i3`, but also by `-nut`, which may possibly be where the difference is caused (I'm not really familiar with indent so mainly guessing here). If this is the case I would suggest changing either the rule in indent.sh, or the suggested command in README.md that uses the -linux option. Obviously the latter would have the least effect on the existing code, but I am unsure which of the styles was the intended one.

**Comment by wolf99** [comment]
Command from `indent.sh`:
~~~sh
$ indent -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i3 -nut 
-ip0 -l80 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -il1
~~~

Command from `README.md` `$ indent -linux -i3` equivalent to:
~~~sh
$ indent -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i8 
-ip0 -l80 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1 -i3
~~~
Where the trailing `-i3` overrides the background `-i8`.

**Comment by wolf99** [comment]
Have tested this now. Made a local branch at a5d8645 and ran `$ indent -linux -i3 -nut $(file)` on the same file. This made changes similar to that which `indent.sh made on 1f32a18. to confirm I did a diff between this local branch and 1f32a18 and the results show there is no difference between them.

Thus I suggest altering the README.md suggested indent command to `$ indent -linux -i3 -nut $(file)`

**Comment by patricksjackson** [comment]
Ok, so all of the options passed to `indent` in `indent.sh` are equivalent to running `indent -linux -i3 -nut`. Updating the docs (and script) to be clear that that's what we're doing is a good thing :+1: 

The idea in #70 was to make a full switch to using just the standard Linux style without modifications, but I'm not sure if there's a ton of drive behind that anymore.
