### ISSUE TITLE
phone-number tests dont check for length greater than 11

### ISSUE THREAD

**Issue by wolf99** [exercism/xc#124]
The problem brief mentions:

> - If the phone number is more than 11 digits assume that it is a bad number

But the tests do not check for this requirement.

**Comment by DeathSec** [comment]
there are phone numbers which is 11 digits ... , for example a landline number 04424611XZ , the first three digits change accordingly

**Comment by DeathSec** [comment]
We cannot actually say how many digits are allowed in phone numbers , it differs from country to country , there are even 11 to 14 digit phone numbers.

**Comment by ryanplusplus** [comment]
@DeathSec I agree, but the purpose of the exercise isn't to be a 100% accurate, production-ready phone number system. The tests should come from here: https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json. If you think there are gaps in the exercise that can be corrected, the place to do it is in the `x-common` repository.

**Comment by wolf99** [comment]
then it's missing a few tests (and has some tests that aren't listed at all in xcommon)

~~~json
      {
        "description": "invalid when 12 digits",
        "phrase": "321234567890",
        "expected": null
      },
      {
        "description": "invalid with letters",
        "phrase": "123-abc-7890",
        "expected": null
      },
      {
        "description": "invalid with punctuations",
        "phrase": "123-@:!-7890",
        "expected": null
      },
      {
        "description": "invalid with right number of digits but letters mixed in",
        "phrase": "1a2b3c4d5e6f7g8h9i0j",
        "expected": null
      }
~~~

The first in the above checks for one of the cases greater than 11 (i.e. 12) but not all. I'll raise an issue for that there, but there remains the fact that the tests for the xc execrcise differs quite a bit from the xcommon spec shown above.

**Comment by ryanplusplus** [comment]
Agreed. We should fix everything up when we address this issue.

**Comment by wolf99** [comment]
The change to x-common repo is made in [#719](https://github.com/exercism/x-common/pull/719). the test case now reads:

```JSON
        {
          "description": "invalid when more than 11 digits",
          "property": "clean",
          "phrase": "321234567890",
          "expected": null
        },
```
