### ISSUE TITLE
atbash-cipher , Valgrind errors.

### ISSUE THREAD

**Issue by DeathSec** [exercism/xc#134]
atbash-cipher exercise , has valgrind errors , it does have memory leaks too , so the whole run-test fails when i ran run-test bash script locally , this will cause fail builds on travis-ci even though other exercises are valid

**Comment by patricksjackson** [comment]
All those errors should have been fixed along with the Valgrind check-in #132.

Please make sure your local branch is up to date with the latest master (rebase on the pr branch and pull into your master). 

If you still see the issue after making sure you're up to date, please let me know what system you're running on.

**Comment by DeathSec** [comment]
The build succeeded in my local system , OS: Arch Linux x86_64 , GCC 6.3.1
