### ISSUE TITLE
Makefiles missing source dependencies

### ISSUE THREAD

**Issue by McFadge** [exercism/xc#19]
Hi all,

New to this, so I'm sorry if I'm missing something obvious, but it seems that all the make files are missing source dependencies? Is it expected for the user to add them?

Also, it seems that it might be useful to include blank source files, especially since there are references to the required files in the Makefiles and test files. I feel like both of these would just be one less step for setting up.

**Comment by kytrinyx** [comment]
I'm not quite sure what the status of this is. This track isn't active, and I don't think that it has been under active development over the past few months.

**Comment by sunzenshen** [comment]
My impression was that there hasn't been a consensus on which build system to use:
https://github.com/exercism/xc/issues/4

With the tests as is, the user is expected to read the test #include(s) in order to figure out which source files to create. An alternative compromise could be to provide a stub header file, and let the participant consider breaking off code into an implementation file.

Either way, if you want to try experimenting with how to provide the build environment, now is a good time as any.

**Comment by kytrinyx** [comment]
A stub header file would work, since any files not named /[Ee]xample/ are delivered to the user when they fetch the exercise.

**Comment by McFadge** [comment]
I began creating stub .h and .c files and including them in the makefile dependencies. However, doing so made me wonder how much we expect to leave to the user. Should the program compile with no work? Should the program compile but pass no tests? Some tests? Should the user be deciding on datatypes?

Just including the dependencies without the source files means you get something like this when running `make`

`make: *** No rule to make target `src/leap.c', needed by `tests.out'.  Stop.`

Which people might be able to interpret correctly as "Hey, you should create this file".

Even including the .h files with just the appropriate function invites some decision of what datatypes to use, or the names of function arguments. But maybe including too much, like a dummy variable to return, would put the user off from modifying existing code.

Personally, I think providing stub files with a blank template for the required function is beneficial. It lets the user focus on solving the problem than having them consider whether they want an int or an unsigned int. Though, this being my first track, I'm not sure what is expected of exercism exercises.

**Comment by kytrinyx** [comment]
In many languages we start the user off with nothing--it doesn't compile, we don't give them hints, and they have to piece together what to define by looking at the error messages and the tests.

We do, however, make sure that the test dependencies are all in place.

I think it's beneficial to have to think about whether you want an int or an unsigned int.

In the Go track we provide lots of hints and a very complete stub file for the first exercise, then we back off little by little.

**Comment by sunzenshen** [comment]
The xcpp repo for C++ is a good place to look for examples: https://github.com/exercism/xcpp/

Specifically, the setup readme provides documentation for how to start with the C++ exercises.

You can also compare the source readme(s) with the final output on the docs page: http://exercism.io/languages/cpp

**Comment by justanotherdot** [comment]
Adding my two cents as @McFadge and I know each other in person and I had mentioned this fledgeling track to him since we're both fans of C.

The C++ track uses cmake in tandem with make. I did create a working CMakeLists.txt yesterday and tested it across the C exercises on linux and OS X from the command line (that is to say, I didn't test it from any common IDEs). I think cmake for C is a bit overkill, though, and it adds a link in the chain.

make seems the path of least resistance and I have the time on my hands to go through and clean things up and maybe add/port a few exercises. Just don't want to make any large steps until people confer unless action is considered to be the consensus.

**Comment by sunzenshen** [comment]
Since the exercise set is still private, I'm all for trying out alternative build setups. May be worth pinging the other folks in this thread: https://github.com/exercism/xc/issues/4

@LegalizeAdulthood , @lpil , @silentbicycle any thoughts about using make (only) versus Cmake?

**Comment by lpil** [comment]
I prefer the idea of using just make.

**Comment by LegalizeAdulthood** [comment]
Here are some of my thoughts:

- The trend for C/C++ projects has been increasingly to use CMake for building.
- CMake can simplify things when using a test framework.
  - You have to locate the include directory for the test framework.
  - You have to locate any compiled libraries for the test framework.
  - You have to specify the library to link against when linking your test executable.
  - CMake does all this in one or two lines of code that are easily explained with a comment.
  - Adding all the necessary parts to a Makefile to achieve the same thing is more arcane and harder to explain (particularly with Makefiles still relying on the TAB character to separate actions from dependency declarations).
- CMake gives you IDE projects for CLion, Visual Studio (any version) and Xcode for free.
- Users preferring make can generate Makefiles from CMake.
- Makefiles don't leverage the strengths of Xcode, CLion or Visual Studio as an IDE.
- Currently, I don't think CLion understands anything but CMake for projects.
- My opinion based on experience is that:
  - Many C developers are unix/linux oriented.
  - They are historically comfortable with Makefiles.
  - They either use fancy editors as primitive IDEs (vim, emacs) or have no experience with IDEs (Xcode, CLion, Visual Studio).
  - This results in a bias towards more antiquated tooling, but newer programmers to C might be more comfortable with the familiarity of IDEs for C coding.

The C++ track specifically instructs you to create empty implementation files as a starting point for the CMake step of creating your build.  Once you've got a Makefile, project file, etc., you need to put the minimal amount of implementation in your files to get the tests to compile --- and then fail.  From that point on, it's straightforward TDD.

Once you've gone through setting up the first exercise, the steps are the same for all subsequent exercises.

**Comment by justanotherdot** [comment]
Playing devil's advocate; some may be turned off from completing exercises if they feel they need to learn how to navigate makefiles in tandem with learning C (and let's face it, C can already be daunting for newcomers to begin with).

@LegalizeAdulthood I actually took your C++ CMakeLists.txt and modified it. Here's the modified version that works with the exercises but I've only tested it using `cmake -G "Unix Makefiles" ..` as I don't really use any IDEs so I'm not sure if it's kosher with any other cmake generators. As such, I don't know if the MSVC line needs to be kept or if it's a C++ specific issue. 

It could probably be cleaned up; I'm not expert in cmake but I kind of know how to get around it. 
[CMakeLists.txt](https://github.com/exercism/xc/files/110523/CMakeLists.txt)

**Comment by LegalizeAdulthood** [comment]
Those compiler flags will only work for GCC flavored compilers.  Also, I'm not sure why you're building optimized, it's useful to use the debugger to step into the tests and your implementation.

You'll want to have someone on VS/MSVC and Xcode testing your build before deploying.

**Comment by justanotherdot** [comment]
Purely force of habit. I don't typically use visual studio but I could set it up easily enough for testing.

**Comment by LegalizeAdulthood** [comment]
For C code, you might want to anticipate that some of the secure CRT warnings can be off-putting to a new programmer:

https://msdn.microsoft.com/en-us/library/8ef0s5kh.aspx

**Comment by divyaantonyjr** [comment]
Here is What i did to compile, its simple
$touch src/leap.c
$make
$./tests.out

thats it , it should compile well....

**Comment by ryanplusplus** [comment]
Looks like all current exercises use `make` and include the source file in the makefile. I agree with sticking with plain old `make` for now since this reduces the number of hurdles to jump over given that learning C is already daunting enough.

I'm going to call this one done for now and if we want to investigate anything further, let's create a new issue to continue the discussion.
