### ISSUE TITLE
[hello-world] name[0] == '\0' vs. name == NULL

### ISSUE THREAD

**Issue by NobbZ** [exercism/xc#33]
Currently the tests as well as the example is implemented as checking the first character of `name` beeing `'\0'`, which makes it impossible to produce the (weird) output `"Hello, !"`.

Even if this output is weird it is valid in many other tracks, and since we are able to in C, I do also think we should resemble a behaviour which comes closer to most other tracks, and actually allow `hello(dest, size, "")` to fill `dest` with that weird string from above while `hello(dest, size, NULL)` will insert `"World"` as name.

Using `NULL` also does come close to other tracks that use some `Maybe` or `Option` type to achieve the behaviour described.

**Comment by patricksjackson** [comment]
It looks to me like the tracks are split between which way to do it. I just checked Python and Java and they both treat the empty string case just like the NULL case.

That being said, in C I agree they are definitely different cases, but it's really a matter of what we want to teach in the Hello World lesson; NULL or string length.

1. Right now, you need to know how to test the length of a string, but don't need to know anything about NULL.
2. If it's switched to allow `'\0'` to result in the output `"Hello, !"`, then you just need to know about NULL and not how to test string length.

Personally, I feel that NULL is the more fundamental concept to teach, so I'd vote to change it.

**Comment by NobbZ** [comment]
To be honest, I think, that languages that can differentiate between an empty string and some kind of nothing, really should do it.

Even though, sometimes languages idioms seem to be very weird as well.

Some time ago I've commented on a python version which had the `name` argument default to `Nil` and then check and conditionally reassign in the functions body. I felt this is breaking the mechanism of default values for arguments but others joined into the disussion and told me, this was idiomatic python. I do not use python, but just tested it out, so I can not really say how idiomatic it really is.

Saying this, I think it will be best to actually continue the discussion over on x-common, I will file an issue over there in a couple of minutes.

**Comment by ryanplusplus** [comment]
@NobbZ I agree that there should be a difference between an empty string and `NULL`/nothing. Given that this is the very first exercise, why don't we just keep this simple and use `NULL`? I think that this better expresses that the name argument is "empty".

I'm going to put a PR together to use `NULL` and plan to address any results from https://github.com/exercism/x-common/issues/290 at a later date.
