### ISSUE TITLE
Does this track have a maintainer?

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#39]
My team at work is interested in populating this track. I'm a maintainer for the Lua track and I'm happy to be a maintainer or the maintainer for this track as well.

**Comment by kytrinyx** [comment]
We don't have a maintainer and I would love to add you (as well as others on your team if they end up getting more than casually involved).

I'll add you now, and you can let me know if/when you see others contributing regularly who should be added.

**Comment by kytrinyx** [comment]
OK, @ryanplusplus, you should have commit on this one now.

**Comment by ryanplusplus** [comment]
Thanks @kytrinyx

**Comment by englishm** [comment]
@ryanplusplus Thanks for working on this! 👍
