### ISSUE TITLE
Choose, document, and use a style guide for provided code

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#40]
Currently there is some inconsistency in formatting/style for the tests and sample solutions. We should choose a style guide, document it in README.md, and ensure that it is applied consistently on the track.

**Comment by ryanplusplus** [comment]
To get things rolling, how about the [Linux kernel style](https://www.kernel.org/doc/Documentation/CodingStyle) but with a more reasonable indent (3 spaces instead of 8)?

In other words, something like this:

```c
static int blah(int a)
   for (i = 0; i < num_elements; i++) {
      foo[i] = foo[i] + 42;
  
      if (foo[i] < 35) {
         printf ("Foo!");
         foo[i]--;
      } else {
         printf ("Bar!");
         foo[i]++;
      }
   }

   return a;
}
```

This is widely used, already documented, and can be auto-formatted using [GNU `indent`](https://www.gnu.org/software/indent/manual/indent.html) on any reasonable OS with the following settings:

```
-nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 
-cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -npsl -sai
-saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts3 -il1
```

We could even integrate a formatting check into our CI build to help us maintain consistent style.

**Comment by patricksjackson** [comment]
I don't think you'll ever get 100% agreement on any coding style, but that looks like a sane set of choices to me, and the autoformatting idea is great :+1: 

I think you have the wrong settings listed for indent though. As far as I can tell you need to remove `-i8` and instead use `-i3 -nut` to get an indentation level of 3 without tabs.

**Comment by ryanplusplus** [comment]
Thanks @patricksjackson. I've updated my post above and will test this out once I'm on my development machine.

**Comment by palisaide** [comment]
I agree that the ability to use a simple program like `indent` is key to enforcing a formatting standard.  At least, it would immediately answer the question "is my code formatted correctly?"  Something that I have often asked myself on other language tracks.

**Comment by ryanplusplus** [comment]
This should also include a preference for C99 features (https://github.com/exercism/xc/issues/53)

**Comment by ryanplusplus** [comment]
This should also include a preference for fixed-width types (https://github.com/exercism/xc/issues/52)

**Comment by patricksjackson** [comment]
Once we update the contributing guide, we need to also document the odd #includes for the example solutions, (writing the code as if the files are named something else) see conversation in #50.
