### ISSUE TITLE
Should we use fixed-width types (e.g. stdint) exclusively?

### ISSUE THREAD

**Issue by palisaide** [exercism/xc#52]
Should we use fixed-width types (e.g. stdint) exclusively or favor primitive types unless a size-guaranteed type is required for the particular exercise?

**Comment by ryanplusplus** [comment]
I personally feel that fixed width types (almost) always make the most sense. So my 2 cents is yes, we should.

**Comment by patricksjackson** [comment]
I agree. The only real downside is adding some confusion for people new to the language, but it will be mostly hidden from them anyways.
