### ISSUE TITLE
For gigasecond, is it more complicated than just adding 1e9 seconds?

### ISSUE THREAD

**Issue by patrickbreen** [exercism/xc#60]
Because simply adding 1e9 seconds works for the other languages, but here it only passes 3/5 tests.

**Comment by patricksjackson** [comment]
It shouldn't be more complicated than that (as long as you're using the `time_t` type). Take a peak at the reference solution in this repo.

(Actually, I just tried it myself with the reference solution and only passed 4/5 tests, there may be something wrong with the test cases. I'll take another look when I get the chance later.)

**Comment by palisaide** [comment]
@patricksjackson, I just tried the example and all of the tests pass for me.  I'm using clang v800.0.38 on OS X 10.11.

**Comment by ryanplusplus** [comment]
@palisaide I tried on gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) and fail the first test. I haven't yet figured out what's wrong.

**Comment by ryanplusplus** [comment]
Interestingly I get a warning about `strptime`:

```
test/test_gigasecond.c:13:4: warning: implicit declaration of function ‘strptime’ [-Wimplicit-function-declaration]
    strptime(str, "%F %T %z", &date);
```

**Comment by ryanplusplus** [comment]
Apparently `strptime` is not available in C99 and is a Unix extension. You need to define `_GNU_SOURCE` and `__USE_XOPEN` on Ubuntu to have `time.h` bring it in. We should probably not use this for the exercise. See #66.
