### ISSUE TITLE
Default Makefile Flags

### ISSUE THREAD

**Issue by patricksjackson** [exercism/xc#61]
While looking into what was happening with #58, I noticed that the default Makefile being copied around doesn't actually use the long list of CFLAGs. (It may also be a reason why the Travis tests are failing in that PR, so we probably need to fix this first.)

In the exercises I checked, enabling it broke the build due to the `-Werror` flag. So rather than just enabling it everywhere, I think we should first agree on which flags we should actually include, and then update the exercises 1 by 1 in case they need changes.

Here are the current flags in the file with a few of my own comments.
```
CFLAGS = -std=c99
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -Werror
CFLAGS += -Wpointer-arith   # Enabled by pedantic
CFLAGS += -Wcast-align  # Might be useful(?) I don't know
CFLAGS += -Wwrite-strings  # Helps for enforcing const char*
CFLAGS += -Wswitch-default  # Maybe, it breaks some of my own code
CFLAGS += -Wunreachable-code  # Removed from GCC
CFLAGS += -Winit-self  # Good (C++ enables this in Wall, but not C)
CFLAGS += -Wmissing-field-initializers  # In -Wextra
CFLAGS += -Wno-unknown-pragmas  # May be good for allowing other compiler pragmas
CFLAGS += -Wstrict-prototypes  # Forces people to use foo(void) instead of foo(), potentially confusing
CFLAGS += -Wundef  # Probably don't need that
CFLAGS += -Wold-style-definition  # In -Wextra
```

I think we should include the following:
```
CFLAGS = -std=c99
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -Wpedantic
CFLAGS += -Werror
```

And it might be a good idea to include some (or all) of these.
```
CFLAGS += -Wwrite-strings  # Helps for enforcing const char*
CFLAGS += -Winit-self  # Good (C++ enables this for Wall, but not C)
CFLAGS += -Wstrict-prototypes  # Forces people to use foo(void) instead of foo(), potentially confusing
```

What do you all think? I don't usually mess around with warnings outside of `-Wall -Wextra -Wpedantic`.

If you need to look up the warning options, [here are GCC's](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)

**Comment by ryanplusplus** [comment]
I think I'm in favor of just going with the short list of general flags:

```
CFLAGS = -std=c99
CFLAGS += -Wall
CFLAGS += -Wextra
CFLAGS += -Wpedantic
CFLAGS += -Werror
```

Those are going to be much more widely used than a lot of the others and will help us to keep our makefiles from being even more frightening.

**Comment by palisaide** [comment]
I vote for including `-Wstrict-prototypes`.  If someone is learning C for the first time, I think it's an important to enforce (what I believe is) a good practice.

**Comment by patricksjackson** [comment]
I'm thinking it may be better to just stick with the short list of flags, but I am admittedly not up to date on Modern C development practices.

What do you think @ryanplusplus ?

**Comment by ryanplusplus** [comment]
My bias is for keeping it simple. Most (all?) warnings have at least _some_ reasonable use so you'll almost always be able to find a reason to include them. We also need to keep in mind that the idea of Exercism is that most people will get feedback on at least some of their exercises so we don't need to rely on the compiler to find every possible mistake.

That said, I'm not ready to die on this hill :)

**Comment by palisaide** [comment]
Good points all around.  I'm in agreement.
