### ISSUE TITLE
Fix existing examples so they pass all tests

### ISSUE THREAD

**Issue by palisaide** [exercism/xc#62]
- [ ] Anagram: Fix 1 failing test
- [x] Leap: Fix 1 failing test
- [x] Leap: Fix 2 compiler warnings

**Comment by ryanplusplus** [comment]
I think the issue with Hello World is that a stub is provided named `hello_world.c`. When you try to rename `example.c` to `hello_world.c` it fails and so runs the tests with the empty implementation and fails all 3 tests. When I tested by removing `hello_world.c` and `example.c` all tests pass.

**Comment by ryanplusplus** [comment]
I don't see any failures for Anagram. What failure are you seeing?

**Comment by palisaide** [comment]
Yep, good call about Hello World.  As for Anagram, I'm getting:
`anagram.c:163:test_multiple_anagrams:FAIL: Expected 3 Was 0`

**Comment by patricksjackson** [comment]
I can't get a failure for Anagram either (Ubuntu 12.04 & 16.04). I even tried it using GCC 4.8, which I think I heard was the version on Travis (?) but that worked fine as well.

I will take a more in-depth look tomorrow and test the failure on Travis.

We need to get this running before putting more exercises in. #71 wouldn't even compile, one of the test names was wrong.

**Comment by palisaide** [comment]
Ok, I'm not sure what was going on before, but Anagram is now working for me.  Maybe fed3ddf fixed it?

**Comment by ryanplusplus** [comment]
I think it's quite likely that it did. I think this is good to go.
