### ISSUE TITLE
Makefile builds do not track dependencies

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#64]
If you change a depended-upon header and re-`make` it will not recompile C files that include that header. We could do this the complicated way and build dep files, or we could weasel out and just add header files as dependencies for the .o build targets. I think that I'm in favor of keeping it simple at this point. Thoughts?

**Comment by patricksjackson** [comment]
I think adding the header files as dependencies is the way to go.

**Comment by palisaide** [comment]
I agree, let's keep it simple.
