### ISSUE TITLE
Gigasecond: strptime is not a C standard function

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xc#66]
`strptime` is not available in vanilla C99 and is a Unix extension (https://www.gnu.org/software/libc/manual/html_node/Parsing-Date-and-Time.html). You need to define `_GNU_SOURCE` and `__USE_XOPEN` on Ubuntu to have `time.h` bring it in. We should remove this to improve compatibility across platforms.

**Comment by ryanplusplus** [comment]
If we want to continue specifying time in terms of date, we can build a `struct tm` and use `mktime` to convert to a `time_t`.

**Comment by patricksjackson** [comment]
Ah, that would explain some of the incompatibilities. (I think they may have been handling daylight savings time differently).

I rewrote one of the tests already to use `mktime()` and it works fine. I'll create a PR to update them all soon.

**Comment by ryanplusplus** [comment]
Excellent. I was hoping that it would solve our other problems.
