### ISSUE TITLE
gigasecond

### ISSUE THREAD

**Issue by qprquo** [exercism/xc#77]
I've got issue with this exercise because I used ming32  that doesnt support __time64__ type. Please, remake test suite for handling __time32__ type. Thank you!

**Comment by patricksjackson** [comment]
The dates for the test suite were chosen in part to illustrate the exact problem you hit. You can always just comment out the tests that use dates after 2038, but I would highly suggest avoiding using a library that can't represent a date that's less than 8000 days from now.

It could use an explanatory comment describing the Year 2038 problem and maybe linking the wikipedia page. That's probably a good idea to have, you could send us a PR if you'd like :)

(If there's a way to force the use of a 64bit `time_t` on 32bit libraries we could do that instead, but I don't know of one.)

**Comment by ryanplusplus** [comment]
:+1:

**Comment by qprquo** [comment]
Ive just installed 64 bit comiler but thank you for advice!

**Comment by patricksjackson** [comment]
No problem :)
